workflows:
  android-apk:
    name: Boodschappen App APK
    max_build_duration: 60
    instance_type: mac_mini_m2

    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"

      - name: Check Android resources
        script: |
          echo "=== CURRENT DIRECTORY ==="
          pwd

          echo "=== ANDROID RESOURCES ==="
          find "$CM_BUILD_DIR/android/app/src/main/res" -type f -print

          echo "=== DRAWABLE ==="
          ls -la "$CM_BUILD_DIR/android/app/src/main/res/drawable"

          echo "=== LAUNCHER FILES ==="
          ls -la "$CM_BUILD_DIR/android/app/src/main/res/drawable"/ic_launcher*

      - name: Build Android APK
        script: |
          cd "$CM_BUILD_DIR/android"
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
